version: '3.6'

networks:
  network:
    driver: bridge

services:
  api:
    build: .
    volumes:
      - .:/home/node/api
    environment:
      - MONGO_URL=db
    depends_on:
      - db
    networks:
      - network
    links:
      - db
    container_name: api
    command: yarn dev
    logging:
      driver: gelf
      options:
        gelf-address: "tcp://localhost:12201"
        tag: 'Log API'
    ports:
      - 3333:3333

  db:
    image: bitnami/mongodb:latest
    container_name: db
    restart: always
    logging:
      driver: gelf
      options:
        gelf-address: "tcp://localhost:12201"
        tag: 'Log DB'
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MONGODB_USERNAME=${MONGO_USER}
      - MONGODB_PASSWORD=${MONGO_PASS}
      - MONGODB_DATABASE=${MONGO_DB}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - network

volumes:
  mongodb_data:
    driver: local